language: php
php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS job_khoj;" -uroot

env:
  global:
    - setup=basic

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction; fi

script: vendor/bin/phpunit